FROM tianon/true
MAINTAINER Benjamin Borbe <bborbe@rocketnews.de>
COPY aptly_dashboard_server /
COPY files /files
COPY ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
EXPOSE 8080
ENTRYPOINT ["/aptly_dashboard_server"]
