FROM golang:1.9
MAINTAINER Benjamin Borbe <bborbe@rocketnews.de>
ARG VERSION
COPY Makefile /
COPY sources /go/src/github.com/bborbe/aptly_dashboard
WORKDIR /
RUN make setup
RUN make buildgo
CMD ["/bin/bash"]
